---
AWSTemplateFormatVersion: 2010-09-09
Description: ---
Parameters: 
  SytemName: 
    Type: String
    Default: tmp
  EnvName:
    Type: String
    Default: dev
Mappings: 
  VpcParameter:
    VPCA:
      VpcCidr: 10.8.0.0/16
    VPCB:
      VpcCidr: 10.9.0.0/16

# Conditions: 
Resources: 
  VPCA:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [ VpcParameter, VPCA, VpcCidr ]
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref SytemName, !Ref EnvName, A, vpc ] ]
  APubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref VPCA
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt VPCA.CidrBlock, 1, 8 ]]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref SytemName, !Ref EnvName, Apub, sn ] ]
  ATGWSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref VPCA
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt VPCA.CidrBlock, 2, 8 ]]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref SytemName, !Ref EnvName, Atgw, sn ] ]
  # BTGWSubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: !Select
  #       - 0
  #       - Fn::GetAZs: !Ref 'AWS::Region'
  #     VpcId: !Ref VPC01
  #     CidrBlock: 10.0.19.1/24
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-A-pub-sn
  # VPCB:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: 10.0.19.0/21
  #     EnableDnsSupport: true
  #     Tags: 
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-B-vpc
  # BPubSubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: !Select
  #       - 0
  #       - Fn::GetAZs: !Ref 'AWS::Region'
  #     VpcId: !Ref VPC01
  #     CidrBlock: 10.0.19.1/24
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-A-pub-sn
  # BTGWSubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: !Select
  #       - 0
  #       - Fn::GetAZs: !Ref 'AWS::Region'
  #     VpcId: !Ref VPC01
  #     CidrBlock: 10.0.19.1/24
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-A-pub-sn
  # TGW:
  #   Type: AWS::EC2::TransitGateway
  #   Properties:
  #     AutoAcceptSharedAttachments: enable
  #     DefaultRouteTableAssociation: enable
  #     DefaultRouteTablePropagation: enable
  #     VpnEcmpSupport: enable
  #     DnsSupport: enable
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-tgw
  # VPCAattachment:
  #   Type: AWS::EC2::TransitGatewayAttachment
  #   Properties:
  #     SubnetIds:
  #       - !Ref SubnetA
  #     TransitGatewayId: !Ref TGW
  #     VpcId: !Ref VPCA
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-A-tgwatch
  # VPCBattachment:
  #   Type: AWS::EC2::TransitGatewayAttachment
  #   Properties:
  #     SubnetIds:
  #       - !Ref SubnetB
  #     TransitGatewayId: !Ref TGW
  #     VpcId: !Ref VPCB
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SytemName}-${EnvName}-B-tgwatch
  # VPCATGWRoute:
  #   Type: "AWS::EC2::Route"
  #   Properties:
  #     RouteTableId: !Ref RouteTableA
  #     DestinationCidrBlock: 10.204.0.0/16
  #     TransitGatewayId: !Ref TGW
  #   DependsOn: VPCAattachment

  # VPCBTGWRoute:
  #   Type: "AWS::EC2::Route"
  #   Properties:
  #     RouteTableId: !Ref RouteTableB
  #     DestinationCidrBlock: 10.192.0.0/16
  #     TransitGatewayId: !Ref TGW
  #   DependsOn: VPCBattachment
# Outputs: