---

repos:
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.56.1 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: .*/.*\.(json|yml|yaml) # 最上位階層のymlファイルを除外