---

AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Get the latest AmazonLinux2 AMI_ID.
  Ec2InstanceType:
    Type: String
    Default: t3.micro
    Description: Free tier instance type.
  Ec2KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
  Prefix:
    Description: Prefix
    Type: String
    Default: template
  VpcCidr:
    Description: Please specify a unique value:<VPCCidr> for your account.
    Type: String
    Default: 10.1.0.0/21
  SubnetType:
    Description: "true=PUBRIC-SUBNET, false=PRIVATE-SUBNET"
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  VPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true  # ssmEndpointで必要
      EnableDnsSupport: true  # ssmEndpointで必要
      Tags:
        - Key: Name
          Value: monitoring-vpc

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref VPC01
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt VPC01.CidrBlock, 4, 8 ]]
      MapPublicIpOnLaunch: !Ref SubnetType
      Tags:
        - Key: Name
          Value: monitoting-pub-subnet

  MainRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: monitoring-rt
      VpcId: !Ref VPC01

  AssRtSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MainRT
      SubnetId: !Ref PrivateSubnet

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref Ec2KeyName
      DisableApiTermination: false
      ImageId: !Ref Ec2ImageId
      InstanceType: !Ref Ec2InstanceType
      Monitoring: false
      # SecurityGroupIds:
      #   - !Ref SSHSG
      SubnetId: !Ref PrivateSubnet
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: monitor-instance
      IamInstanceProfile: AmazonSSMManagedInstanceCore

## endpoint sg
  SSMEndpointSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VPC01
      GroupName: !Sub "${Prefix}-ssm-endpoint-sg"
      GroupDescription: !Sub "${Prefix}-ssm-endpoint-sg"
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-ssm-endpoint-sg"

# CidrIpでVPCのIPを指定したいが、これで作成可能か未検証
  SSMEndpointSGIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref SSMEndpointSG
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      # 以下修正必須
      # CidrIp: 0.0.0.0/0
      CidrIp: !Ref VpcCidr

## ----------------------------------------------------------
## Endpoint
## ----------------------------------------------------------
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId: !Ref VPC01
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SSMEndpointSG
  EC2MessageEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2messages"
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId: !Ref VPC01
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SSMEndpointSG
  SSMAgentEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessages"
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId: !Ref VPC01
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SSMEndpointSG

  VPCS3Endpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcEndpointType: Interface
      # PrivateDnsEnabled: true  # interface型のs3privatelinkでは使用できない
      VpcId: !Ref VPC01
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SSMEndpointSG