---

AWSTemplateFormatVersion: 2010-09-09
Description: ---

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !ImportValue Ec2KeyName
      DisableApiTermination: false
      ImageId: !ImportValue Ec2ImageId
      InstanceType: !Ref Ec2InstanceType
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue SSHSG
      SubnetId: !ImportValue PubSubnet
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: monitor-instance

  InstanceEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !ImportValue myEC2Instance
      Tags:
        - Key: Name
          Value: monitor-instance

Outputs:
  myEC2Instance:
    Value: !Ref myEC2Instance