---

AWSTemplateFormatVersion: "2010-09-09"
Description: ---

Resources:
  VPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.8.0/21
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: monitoring-vpc

  PubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref VPC01
      CidrBlock: 10.0.8.1/24
      Tags:
        - Key: Name
          Value: monitoting-pub-subnet

  MainIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: monitoring-igw

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MainIGW
      VpcId: !Ref VPC01

  MainRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: monitoring-rt
      VpcId: !Ref VPC01

  MainR:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MainRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainIGW

  AssRtSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MainRT
      SubnetId: !Ref PubSubnet

Outputs:
  VPC01:
    Value: !Ref VPC01
  PubSubnet:
    Value: !Ref PubSubnet
